# Multi Operating System (mOS)
# Copyright (c) 2016, Intel Corporation.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

hostprogs := lwkreset
scriptprogs-y := lwkreset.sh lwkreset.1.man
lwkreset-objs := lwkreset.o

lwkreset.sh_installname := lwkreset
lwkreset.sh_installpath := /usr/bin
lwkreset.1.man_installname := lwkreset.1
lwkreset.1.man_installpath := /usr/share/man/man1

include $(src)/../Makefile.tool
