.\"                                      Hey, EMACS: -*- nroff -*-
.\" -------------------------------------------------------------------------
.\" Multi Operating System (mOS)
.\" Copyright (c) 2017, Intel Corporation.
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms and conditions of the GNU General Public License,
.\" version 2, as published by the Free Software Foundation.
.\"
.\" This program is distributed in the hope it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
.\" more details.
.\" -------------------------------------------------------------------------
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MOS_GET_ADDR_INFO 2
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mos_get_addr_info \- TBD
.SH SYNOPSIS
.B TBD
.SH DESCRIPTION

TBD

.SH RETURN VALUE
TBD

.SH ERRORS
TBD

.SH NOTES
TBD


.SH COPYRIGHT
Copyright \(co 2017 Intel Corp.
